

# pr:
# - main

pool:
  vmImage: ubuntu-latest

variables:
  PYTHON: 'python3.8'
  INC_VER: '1.12'
  IMAGE_NAME: 'neural-compressor'
  IMAGE_TAG: '1.12'
  INC_BRANCH: 'master'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: Docker@2
      displayName: 'Login to repo'
      inputs:
        command: login
        containerRegistry: inc-internal
        
    - script: docker build --build-arg PYTHON=${PYTHON} --build-arg INC_BRANCH=${INC_BRANCH} -f docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
      displayName: 'Build Container'

- stage: Tuning
  dependsOn: Build
  displayName: Tuning
  jobs:
  - job: MobileNetV2
    displayName: MobileNetV2
    steps:
      # - script: 
      #     cd examples/pytorch/image_recognition/MobileNetV2-0.35/distillation/eager
      #   displayName: 'change dir'
      - script: 
          pip install -r examples/pytorch/image_recognition/MobileNetV2-0.35/distillation/eager/requirements.txt
        displayName: 'Install requirements'
      - script: 
          python -u examples/pytorch/image_recognition/MobileNetV2-0.35/distillation/eager/train_without_distillation.py 
          --epochs 200 --lr 0.1 --layers 40 --widen-factor 2 --name WideResNet-40-2 --tensorboard
        displayName: 'Training teacher model WideResNet40-2'  
      - script:
          python -u examples/pytorch/image_recognition/MobileNetV2-0.35/distillation/eager/main.py 
          --epochs 200 --lr 0.02 --name MobileNetV2-0.35-distillation --teacher_model examples/pytorch/image_recognition/MobileNetV2-0.35/distillation/eager/runs/WideResNet-40-2/model_best.pth.tar --tensorboard --seed 9
        displayName: 'Distillation'
    