

# pr:
# - main

pool:
  vmImage: ubuntu-latest

variables:
  PYTHON: 'python3.8'
  INC_VER: '1.12'
  IMAGE_NAME: 'neural-compressor'
  IMAGE_TAG: '1.12'
  INC_BRANCH: 'master'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: Docker@2
      displayName: 'Login to repo'
      inputs:
        command: login
        containerRegistry: inc-internal
        
    - script: docker build --build-arg PYTHON=${PYTHON} --build-arg INC_BRANCH=${INC_BRANCH} -f docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
      displayName: 'Build Container'

- stage: Tuning
  dependsOn: Build
  displayName: Tuning
  jobs:
  - job: MobileNetV2
    displayName: MobileNetV2
    steps:
      - script: 
          ./my_test.sh
        displayName: 'Tuning MobileNet'
    